import {
  LayoutDashboard,
  Users,
  Inbox,
  UserCheck,
  Flame,
  XCircle,
  RefreshCw,
  UserPlus,
  CalendarClock,
  Trophy,
  UsersRound,
  FileText,
  Clock,
  CheckCircle2,
  XOctagon,
  BarChart3,
  Calendar,
  Bell,
  User,
  MapPin,
} from 'lucide-react';

export const salesManagerNavItems = [
  { path: '/sales-manager/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  {
    id: 'lead-management',
    label: 'Lead Management',
    icon: Users,
    children: [
      { path: '/sales-manager/leads/all', label: 'All Team Leads', icon: Users, countKey: 'leads.all' },
      { path: '/sales-manager/leads/unassigned', label: 'Unassigned Leads', icon: Inbox, badgeKey: 'leads.unassigned' },
      { path: '/sales-manager/leads/assigned', label: 'Assigned Leads', icon: UserCheck, countKey: 'leads.assigned' },
      { path: '/sales-manager/leads/hot', label: 'Hot Leads', icon: Flame, badgeKey: 'leads.hot' },
      { path: '/sales-manager/leads/lost', label: 'Lost Leads', icon: XCircle, countKey: 'leads.lost' },
      { path: '/sales-manager/reactivated-leads', label: 'Reactivated Leads', icon: RefreshCw },
    ],
  },
  { path: '/sales-manager/assignment', label: 'Lead Assignment', icon: UserPlus, badgeKey: 'assignment' },
  { path: '/sales-manager/destination-assignment', label: 'Destination Assignment', icon: MapPin },
  { path: '/sales-manager/teams', label: 'Team Management', icon: UsersRound },
  { path: '/sales-manager/follow-ups', label: 'Follow-up Monitoring', icon: CalendarClock, badgeKey: 'followups.due' },
  { path: '/sales-manager/team', label: 'Team Performance', icon: Trophy },
  {
    id: 'quotations',
    label: 'Quotations',
    icon: FileText,
    children: [
      { path: '/sales-manager/quotations/pending', label: 'Pending Approval', icon: Clock, badgeKey: 'quotations.pending' },
      { path: '/sales-manager/quotations/approved', label: 'Approved Quotes', icon: CheckCircle2, countKey: 'quotations.approved' },
      { path: '/sales-manager/quotations/rejected', label: 'Rejected Quotes', icon: XOctagon, countKey: 'quotations.rejected' },
    ],
  },
  { path: '/sales-manager/reports', label: 'Reports', icon: BarChart3 },
  { path: '/sales-manager/calendar', label: 'Calendar', icon: Calendar, badgeKey: 'calendar.today' },
  { path: '/sales-manager/notifications', label: 'Notifications', icon: Bell, badgeKey: 'notifications.unread' },
  { path: '/sales-manager/profile', label: 'Profile', icon: User },
];
