import {
  Building2,
  CreditCard,
  FileText,
  Globe,
  LayoutDashboard,
  LifeBuoy,
  Megaphone,
  Network,
  SlidersHorizontal,
  Puzzle,
  Receipt,
  Settings,
  Shield,
  BarChart3,
  Wallet,
  Mountain,
  Home,
  MapPin,
  Tags,
  Newspaper,
  Image,
  Images,
  MessageSquareQuote,
  CircleHelp,
  Menu,
  Search,
  Inbox,
  TicketPercent,
  Cog,
  ArrowRightLeft,
  ScrollText,
} from 'lucide-react';

export const NAV_SECTIONS = [
  {
    label: 'Platform',
    items: [
      { to: '/admin', label: 'Dashboard', icon: LayoutDashboard, end: true },
      { to: '/admin/companies', label: 'Companies', icon: Building2 },
      { to: '/admin/subscriptions', label: 'Subscriptions', icon: CreditCard },
      { to: '/admin/payment-requests', label: 'Payment Requests', icon: Wallet, badgeKey: 'payments' },
      { to: '/admin/plans', label: 'Plans', icon: Receipt },
      { to: '/admin/features', label: 'Platform Features', icon: SlidersHorizontal },
      { to: '/admin/plans', label: 'Add-ons', icon: Puzzle },
    ],
  },
  {
    label: 'Infrastructure',
    items: [
      { to: '/admin/domains', label: 'Domains', icon: Globe },
      { to: '/admin/dns', label: 'DNS Verification', icon: Network },
      { to: '/admin/invoices', label: 'Invoices', icon: FileText },
      { to: '/admin/settings', label: 'Payment Gateways', icon: Wallet },
    ],
  },
  {
    label: 'Operations',
    items: [
      { to: '/admin/support', label: 'Support Tickets', icon: LifeBuoy, badgeKey: 'tickets' },
      { to: '/admin/announcements', label: 'Announcements', icon: Megaphone },
      { to: '/admin/reports', label: 'Reports', icon: BarChart3 },
      { to: '/admin/logs', label: 'Audit Logs', icon: Shield },
    ],
  },
  {
    label: 'Website Management',
    items: [
      { to: '/admin/website', label: 'Dashboard', icon: LayoutDashboard, end: true },
      { to: '/admin/website/homepage', label: 'Homepage', icon: Home },
      { to: '/admin/website/treks', label: 'Trek Management', icon: Mountain },
      { to: '/admin/website/destinations', label: 'Destinations', icon: MapPin },
      { to: '/admin/website/categories', label: 'Categories', icon: Tags },
      { to: '/admin/website/blogs', label: 'Blogs', icon: Newspaper },
      { to: '/admin/website/media', label: 'Media Library', icon: Image },
      { to: '/admin/website/gallery', label: 'Gallery', icon: Images },
      { to: '/admin/website/testimonials', label: 'Testimonials', icon: MessageSquareQuote },
      { to: '/admin/website/faqs', label: 'FAQs', icon: CircleHelp },
      { to: '/admin/website/menus', label: 'Menus', icon: Menu },
      { to: '/admin/website/seo', label: 'SEO Management', icon: Search },
      { to: '/admin/website/leads', label: 'Forms & Leads', icon: Inbox },
      { to: '/admin/website/coupons', label: 'Coupons', icon: TicketPercent },
      { to: '/admin/website/settings', label: 'Website Settings', icon: Cog },
      { to: '/admin/website/redirects', label: 'Redirect Manager', icon: ArrowRightLeft },
      { to: '/admin/website/activity', label: 'Activity Logs', icon: ScrollText },
    ],
  },
];

export const SETTINGS_NAV = { to: '/admin/settings', label: 'Settings', icon: Settings };
