import {
  LayoutDashboard,
  Users,
  Inbox,
  UserCheck,
  CalendarClock,
  Trophy,
  XCircle,
  RefreshCw,
  MessageCircle,
  FileText,
  Mail,
  Globe2,
  UsersRound,
  BarChart3,
  Calendar,
  Bell,
  Settings,
  Clock,
  MapPin,
  Award,
  BarChart2,
  Shield,
  Archive,
  Timer,
  Briefcase,
  Plane,
  CreditCard,
  ListTodo,
} from 'lucide-react';
import { operationsAdminMenuChildren } from '../operations-manager/operations-nav-config';

export const reportsAnalyticsItems = [
  { path: '/reports', label: 'Reports', icon: BarChart3, permission: { module: 'reports', action: 'view' } },
  {
    path: '/leads/analytics',
    label: 'Lead Analytics',
    icon: BarChart2,
    roles: ['admin', 'sales_manager', 'team_leader'],
    permission: { module: 'leads', action: 'view' },
  },
  {
    path: '/leads/sla',
    label: 'SLA Monitor',
    icon: Timer,
    roles: ['admin', 'sales_manager', 'team_leader'],
    permission: { module: 'leads', action: 'view' },
  },
];

export const settingsMenuItems = [
  { path: '/settings', label: 'General Settings', icon: Settings },
  {
    path: '/settings/email-templates',
    label: 'Email Templates',
    icon: Mail,
    permission: { module: 'email', action: 'manage' },
  },
  {
    path: '/settings/whatsapp-templates',
    label: 'WhatsApp Templates',
    icon: MessageCircle,
    permission: { module: 'whatsapp', action: 'manage' },
  },
  {
    path: '/notifications',
    label: 'Notifications',
    icon: Bell,
    badgeKey: 'notifications.unread',
    permission: { module: 'leads', action: 'view' },
  },
];

export const teamManagementItems = [
  {
    path: '/team',
    label: 'Users & Roles',
    icon: UsersRound,
    permission: { module: 'users', action: 'view' },
  },
  {
    path: '/team/attendance',
    label: 'Attendance',
    icon: Clock,
    roles: ['admin'],
  },
  {
    path: '/team/destination-assignment',
    label: 'Destination Assignment',
    icon: MapPin,
    roles: ['admin', 'sales_manager'],
  },
  {
    path: '/team/skill-assignment',
    label: 'Skill Assignment',
    icon: Award,
    roles: ['admin', 'sales_manager'],
  },
];

export const leadManagementItems = [
  { path: '/leads', label: 'All Leads', icon: Users, countKey: 'leads.all', permission: { module: 'leads', action: 'view' } },
  { path: '/leads/new-leads', label: "Today's Leads", icon: Inbox, badgeKey: 'leads.new', permission: { module: 'leads', action: 'view' } },
  { path: '/leads/unassigned', label: 'Unassigned Leads', icon: Inbox, badgeKey: 'leads.unassigned', permission: { module: 'leads', action: 'view' } },
  { path: '/leads/assigned', label: 'Assigned Leads', icon: UserCheck, countKey: 'leads.assigned', permission: { module: 'leads', action: 'view' } },
  { path: '/followups', label: 'Follow Ups', icon: CalendarClock, badgeKey: 'followups.due', countKey: 'followups.total', permission: { module: 'leads', action: 'view' } },
  { path: '/reminders', label: 'Reminder Center', icon: Bell, badgeKey: 'reminders.overdue', permission: { module: 'leads', action: 'view' } },
  { path: '/leads/analytics', label: 'Lead Analytics', icon: BarChart2, roles: ['admin', 'sales_manager', 'team_leader'], permission: { module: 'leads', action: 'view' } },
  { path: '/leads/sla', label: 'SLA Monitor', icon: Timer, roles: ['admin', 'sales_manager', 'team_leader'], permission: { module: 'leads', action: 'view' } },
  { path: '/leads/recycle-bin', label: 'Recycle Bin', icon: Archive, roles: ['admin', 'sales_manager'], permission: { module: 'leads', action: 'view' } },
  { path: '/leads/audit-log', label: 'Audit Log', icon: Shield, roles: ['admin', 'sales_manager'], permission: { module: 'leads', action: 'view' } },
  { path: '/leads/converted', label: 'Converted Leads', icon: Trophy, countKey: 'leads.converted', permission: { module: 'leads', action: 'view' } },
  { path: '/leads/lost', label: 'Lost Leads', icon: XCircle, countKey: 'leads.lost', permission: { module: 'leads', action: 'view' } },
  { path: '/leads/reactivated', label: 'Reactivated Leads', icon: RefreshCw, permission: { module: 'leads', action: 'view' } },
  { path: '/whatsapp', label: 'WhatsApp Leads', icon: MessageCircle, countKey: 'leads.whatsapp', permission: { module: 'leads', action: 'view' } },
];

export const mainNavItems = [
  { path: '/admin/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  {
    id: 'lead-management',
    label: 'Lead Management',
    icon: Users,
    countKey: 'leads.all',
    children: leadManagementItems,
  },
  {
    id: 'operations-management',
    label: 'Operations Management',
    icon: Briefcase,
    roles: ['admin'],
    permission: { module: 'operations', action: 'view' },
    countKey: 'bookings.pending',
    children: operationsAdminMenuChildren,
  },
  {
    path: '/quotations',
    label: 'Quotations',
    icon: FileText,
    badgeKey: 'quotations.pending',
    permission: { module: 'quotations', action: 'view' },
  },
  {
    path: '/packages',
    label: 'Packages',
    icon: Globe2,
    countKey: 'packages',
    permission: { module: 'packages', action: 'view' },
  },
  {
    path: '/operations-manager/bookings/pending',
    label: 'Bookings',
    icon: Plane,
    roles: ['admin'],
    countKey: 'bookings.pending',
    permission: { module: 'operations', action: 'view' },
  },
  {
    path: '/payments',
    label: 'Payments',
    icon: CreditCard,
    roles: ['admin', 'accountant'],
  },
  {
    path: '/email-activity',
    label: 'Email Activity',
    icon: Mail,
    permission: { module: 'email', action: 'send' },
  },
  {
    path: '/followups',
    label: 'Tasks & Follow-ups',
    icon: ListTodo,
    badgeKey: 'followups.due',
    countKey: 'followups.total',
    permission: { module: 'leads', action: 'view' },
  },
  { path: '/calendar', label: 'Calendar', icon: Calendar, badgeKey: 'calendar.today' },
  {
    id: 'reports-analytics',
    label: 'Reports & Analytics',
    icon: BarChart3,
    children: reportsAnalyticsItems,
    permission: { module: 'reports', action: 'view' },
  },
  {
    id: 'team-management',
    label: 'Team Management',
    icon: UsersRound,
    children: teamManagementItems,
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    children: settingsMenuItems,
  },
];
