const express = require('express');
const dataSyncMiddleware = require('../middleware/dataSyncMiddleware');
const { resolveTenant } = require('../middleware/tenantContext');
const router = express.Router();

router.use(dataSyncMiddleware);
router.use(resolveTenant);

const authRoutes = require('./authRoutes');
const leadRoutes = require('./leadRoutes');
const followUpRoutes = require('./followUpRoutes');
const quotationRoutes = require('./quotationRoutes');
const packageRoutes = require('./packageRoutes');
const unoHotelsPackageRoutes = require('./unoHotelsPackageRoutes');
const unoHotelsHotelRoutes = require('./unoHotelsHotelRoutes');
const hotelRoutes = require('./hotelRoutes');
const cabRoutes = require('./cabRoutes');
const flightRoutes = require('./flightRoutes');
const activityRoutes = require('./activityRoutes');
const userRoutes = require('./userRoutes');
const roleRoutes = require('./roleRoutes');
const whatsappRoutes = require('./whatsappRoutes');
const paymentRoutes = require('./paymentRoutes');
const notificationRoutes = require('./notificationRoutes');
const teamRoutes = require('./teamRoutes');
const teamsRoutes = require('./teamsRoutes');
const operationsRoutes = require('./operationsRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const salesExecutiveRoutes = require('./salesExecutiveRoutes');
const salesManagerRoutes = require('./salesManagerRoutes');
const teamLeaderRoutes = require('./teamLeaderRoutes');
const activityLogRoutes = require('./activityLogRoutes');
const reportsRoutes = require('./reportsRoutes');
const inviteRoutes = require('./inviteRoutes');
const navCountsRoutes = require('./navCountsRoutes');
const attendanceRoutes = require('./attendanceRoutes');
const destinationAssignmentRoutes = require('./destinationAssignmentRoutes');
const skillAssignmentRoutes = require('./skillAssignmentRoutes');
const assignmentConfigRoutes = require('./assignmentConfigRoutes');
const reminderRoutes = require('./reminderRoutes');
const whatsappTemplateRoutes = require('./whatsappTemplateRoutes');
const emailTemplateRoutes = require('./emailTemplateRoutes');
const emailRoutes = require('./emailRoutes');
const salesTargetRoutes = require('./salesTargetRoutes');
const tenantRoutes = require('./tenantRoutes');
const publicRoutes = require('./publicRoutes');
const companySettingsRoutes = require('./companySettingsRoutes');

router.use('/auth', authRoutes);
router.use('/public', publicRoutes);
router.use('/tenant', tenantRoutes);
router.use('/invites', inviteRoutes);
router.use('/leads', leadRoutes);
router.use('/followups', followUpRoutes);
router.use('/reminders', reminderRoutes);
router.use('/quotations', quotationRoutes);
router.use('/packages', packageRoutes);
router.use('/uno-packages', unoHotelsPackageRoutes);
router.use('/uno-hotels', unoHotelsHotelRoutes);
router.use('/hotels', hotelRoutes);
router.use('/cabs', cabRoutes);
router.use('/flights', flightRoutes);
router.use('/activities', activityRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/whatsapp-templates', whatsappTemplateRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/emails', emailRoutes);
router.use('/sales-targets', salesTargetRoutes);
router.use('/payments', paymentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/team', teamRoutes);
router.use('/teams', teamsRoutes);
router.use('/operations-manager', operationsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/sales-executive', salesExecutiveRoutes);
router.use('/sales-manager', salesManagerRoutes);
router.use('/team-leader', teamLeaderRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/reports', reportsRoutes);
router.use('/nav-counts', navCountsRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/company-settings', companySettingsRoutes);
router.use('/destination-assignment', destinationAssignmentRoutes);
router.use('/skill-assignment', skillAssignmentRoutes);
router.use('/assignment', assignmentConfigRoutes);

module.exports = router;
