const express = require('express');
const authRoutes = require('./authRoutes');
const companyRoutes = require('./companyRoutes');
const planRoutes = require('./planRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const settingsRoutes = require('./settingsRoutes');
const logsRoutes = require('./logsRoutes');
const notificationRoutes = require('./notificationRoutes');
const domainRoutes = require('./domainRoutes');
const subscriptionRoutes = require('./subscriptionRoutes');
const supportRoutes = require('./supportRoutes');
const announcementRoutes = require('./announcementRoutes');
const invoiceRoutes = require('./invoiceRoutes');
const apiKeyRoutes = require('./apiKeyRoutes');
const adminRoutes = require('./adminRoutes');
const reportsRoutes = require('./reportsRoutes');
const platformFeatureRoutes = require('./platformFeatureRoutes');
const paymentRequestRoutes = require('./paymentRequestRoutes');
const websiteRoutes = require('../website/routes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/companies', companyRoutes);
router.use('/plans', planRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/domains', domainRoutes);
router.use('/support', supportRoutes);
router.use('/announcements', announcementRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/api-keys', apiKeyRoutes);
router.use('/admins', adminRoutes);
router.use('/reports', reportsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingsRoutes);
router.use('/logs', logsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/platform-features', platformFeatureRoutes);
router.use('/payment-requests', paymentRequestRoutes);
router.use('/website', websiteRoutes);

module.exports = router;
