import { api } from './axios';

export const superAdminApi = {
  login: (email, password) => api.post('/auth/login', { email, password }),
  logout: () => api.post('/auth/logout'),
  getMe: () => api.get('/auth/me'),
  getDashboard: () => api.get('/dashboard'),
  listCompanies: (params) => api.get('/companies', { params }),
  getCompany: (id) => api.get(`/companies/${id}`),
  getCompanyUsers: (id) => api.get(`/companies/${id}/users`),
  createCompany: (data) => api.post('/companies', data),
  updateCompany: (id, data) => api.patch(`/companies/${id}`, data),
  deleteCompany: (id) => api.delete(`/companies/${id}`),
  bulkCompanies: (data) => api.post('/companies/bulk', data),
  exportCompanies: (params) => api.get('/companies/export', { params }),
  impersonate: (id) => api.post(`/companies/${id}/impersonate`),
  resetPassword: (id, data) => api.post(`/companies/${id}/reset-password`, data),
  upgradePlan: (id, data) => api.post(`/companies/${id}/upgrade-plan`, data),
  renewSubscription: (id, data) => api.post(`/companies/${id}/renew`, data),
  listPaymentRequests: (params) => api.get('/payment-requests', { params }),
  approvePaymentRequest: (id, data) => api.post(`/payment-requests/${id}/approve`, data),
  rejectPaymentRequest: (id, data) => api.post(`/payment-requests/${id}/reject`, data),
  listPlans: () => api.get('/plans'),
  getPlan: (id) => api.get(`/plans/${id}`),
  createPlan: (data) => api.post('/plans', data),
  updatePlan: (id, data) => api.patch(`/plans/${id}`, data),
  deletePlan: (id) => api.delete(`/plans/${id}`),
  listSubscriptions: (params) => api.get('/subscriptions', { params }),
  listDomains: (params) => api.get('/domains', { params }),
  listPendingDns: () => api.get('/domains/pending'),
  getCompanyDomain: (companyId) => api.get(`/domains/${companyId}`),
  connectDomain: (companyId, data) => api.post(`/domains/${companyId}/connect`, data),
  verifyDomain: (companyId) => api.post(`/domains/${companyId}/verify`),
  refreshDomain: (companyId) => api.post(`/domains/${companyId}/refresh`),
  disconnectDomain: (companyId) => api.post(`/domains/${companyId}/disconnect`),
  updateCompanyDomain: (companyId, data) => api.patch(`/domains/${companyId}`, data),
  listInvoices: (params) => api.get('/invoices', { params }),
  generateInvoice: (data) => api.post('/invoices/generate', data),
  listSupportTickets: (params) => api.get('/support', { params }),
  getSupportTicket: (id) => api.get(`/support/${id}`),
  updateSupportTicket: (id, data) => api.patch(`/support/${id}`, data),
  listAnnouncements: () => api.get('/announcements'),
  createAnnouncement: (data) => api.post('/announcements', data),
  updateAnnouncement: (id, data) => api.patch(`/announcements/${id}`, data),
  deleteAnnouncement: (id) => api.delete(`/announcements/${id}`),
  listAdmins: () => api.get('/admins'),
  createAdmin: (data) => api.post('/admins', data),
  updateProfile: (data) => api.patch('/admins/profile', data),
  listApiKeys: () => api.get('/api-keys'),
  createApiKey: (data) => api.post('/api-keys', data),
  revokeApiKey: (id) => api.post(`/api-keys/${id}/revoke`),
  getReports: () => api.get('/reports'),
  getBackups: () => api.get('/reports/backups'),
  getSettings: (category) => api.get('/settings', { params: { category } }),
  patchSettings: (settings) => api.patch('/settings', { settings }),
  getAuditLogs: (params) => api.get('/logs/audit', { params }),
  getLoginLogs: (params) => api.get('/logs/login', { params }),
  getNotifications: (params) => api.get('/notifications', { params }),
  markNotificationsRead: (body) => api.post('/notifications/read', body),
  getPlatformFeatures: () => api.get('/platform-features'),
  savePlatformFeatureDefaults: (data) => api.patch('/platform-features/defaults', data),
  rolloutPlatformFeatures: (data) => api.post('/platform-features/rollout', data),

  // Website Management
  getWebsiteDashboard: () => api.get('/website/dashboard'),
  listHomepageSections: () => api.get('/website/homepage'),
  upsertHomepageSection: (data) => api.post('/website/homepage', data),
  updateHomepageSection: (id, data) => api.patch(`/website/homepage/${id}`, data),
  deleteHomepageSection: (id) => api.delete(`/website/homepage/${id}`),
  reorderHomepageSections: (orders) => api.post('/website/homepage/reorder', { orders }),

  listWebsiteTreks: (params) => api.get('/website/treks', { params }),
  getWebsiteTrek: (id) => api.get(`/website/treks/${id}`),
  createWebsiteTrek: (data) => api.post('/website/treks', data),
  updateWebsiteTrek: (id, data) => api.patch(`/website/treks/${id}`, data),
  deleteWebsiteTrek: (id) => api.delete(`/website/treks/${id}`),
  duplicateWebsiteTrek: (id) => api.post(`/website/treks/${id}/duplicate`),
  scheduleWebsiteTrek: (id, data) => api.post(`/website/treks/${id}/schedule`, data),
  archiveWebsiteTrek: (id) => api.post(`/website/treks/${id}/archive`),

  listWebsiteDestinations: (params) => api.get('/website/destinations', { params }),
  getWebsiteDestination: (id) => api.get(`/website/destinations/${id}`),
  createWebsiteDestination: (data) => api.post('/website/destinations', data),
  updateWebsiteDestination: (id, data) => api.patch(`/website/destinations/${id}`, data),
  deleteWebsiteDestination: (id) => api.delete(`/website/destinations/${id}`),
  duplicateWebsiteDestination: (id) => api.post(`/website/destinations/${id}/duplicate`),

  listWebsiteCategories: (params) => api.get('/website/categories', { params }),
  createWebsiteCategory: (data) => api.post('/website/categories', data),
  updateWebsiteCategory: (id, data) => api.patch(`/website/categories/${id}`, data),
  deleteWebsiteCategory: (id) => api.delete(`/website/categories/${id}`),

  listWebsiteBlogs: (params) => api.get('/website/blogs', { params }),
  getWebsiteBlog: (id) => api.get(`/website/blogs/${id}`),
  createWebsiteBlog: (data) => api.post('/website/blogs', data),
  updateWebsiteBlog: (id, data) => api.patch(`/website/blogs/${id}`, data),
  deleteWebsiteBlog: (id) => api.delete(`/website/blogs/${id}`),
  autosaveWebsiteBlog: (id, data) => api.post(`/website/blogs/${id}/autosave`, data),
  restoreWebsiteBlogRevision: (id, revisionId) => api.post(`/website/blogs/${id}/revisions/${revisionId}/restore`),
  duplicateWebsiteBlog: (id) => api.post(`/website/blogs/${id}/duplicate`),

  listWebsiteMedia: (params) => api.get('/website/media', { params }),
  uploadWebsiteMedia: (data) => api.post('/website/media/upload', data),
  createWebsiteMediaFolder: (folder) => api.post('/website/media/folders', { folder }),
  updateWebsiteMedia: (id, data) => api.patch(`/website/media/${id}`, data),
  deleteWebsiteMedia: (id) => api.delete(`/website/media/${id}`),
  bulkDeleteWebsiteMedia: (ids) => api.post('/website/media/bulk-delete', { ids }),

  listWebsiteGalleries: (params) => api.get('/website/galleries', { params }),
  createWebsiteGallery: (data) => api.post('/website/galleries', data),
  updateWebsiteGallery: (id, data) => api.patch(`/website/galleries/${id}`, data),
  deleteWebsiteGallery: (id) => api.delete(`/website/galleries/${id}`),

  listWebsiteTestimonials: (params) => api.get('/website/testimonials', { params }),
  createWebsiteTestimonial: (data) => api.post('/website/testimonials', data),
  updateWebsiteTestimonial: (id, data) => api.patch(`/website/testimonials/${id}`, data),
  deleteWebsiteTestimonial: (id) => api.delete(`/website/testimonials/${id}`),

  listWebsiteFaqs: (params) => api.get('/website/faqs', { params }),
  createWebsiteFaq: (data) => api.post('/website/faqs', data),
  updateWebsiteFaq: (id, data) => api.patch(`/website/faqs/${id}`, data),
  deleteWebsiteFaq: (id) => api.delete(`/website/faqs/${id}`),
  reorderWebsiteFaqs: (orders) => api.post('/website/faqs/reorder', { orders }),

  listWebsiteMenus: () => api.get('/website/menus'),
  updateWebsiteMenu: (id, data) => api.patch(`/website/menus/${id}`, data),

  listWebsiteSeo: (params) => api.get('/website/seo', { params }),
  upsertWebsiteSeo: (data) => api.post('/website/seo', data),
  updateWebsiteSeo: (id, data) => api.patch(`/website/seo/${id}`, data),
  syncWebsiteSeo: () => api.post('/website/seo/sync'),
  deleteWebsiteSeo: (id) => api.delete(`/website/seo/${id}`),

  listWebsiteLeads: (params) => api.get('/website/leads', { params }),
  updateWebsiteLead: (id, data) => api.patch(`/website/leads/${id}`, data),
  assignWebsiteLead: (id, data) => api.post(`/website/leads/${id}/assign`, data),
  deleteWebsiteLead: (id) => api.delete(`/website/leads/${id}`),
  exportWebsiteLeads: (params) => api.get('/website/leads/export', { params, responseType: 'blob' }),

  listWebsiteReviews: (params) => api.get('/website/reviews', { params }),
  moderateWebsiteReview: (id, data) => api.patch(`/website/reviews/${id}`, data),
  deleteWebsiteReview: (id) => api.delete(`/website/reviews/${id}`),

  listWebsiteCoupons: (params) => api.get('/website/coupons', { params }),
  createWebsiteCoupon: (data) => api.post('/website/coupons', data),
  updateWebsiteCoupon: (id, data) => api.patch(`/website/coupons/${id}`, data),
  deleteWebsiteCoupon: (id) => api.delete(`/website/coupons/${id}`),

  getWebsiteSettings: () => api.get('/website/settings'),
  updateWebsiteSettings: (data) => api.patch('/website/settings', data),

  listWebsiteRedirects: (params) => api.get('/website/redirects', { params }),
  createWebsiteRedirect: (data) => api.post('/website/redirects', data),
  updateWebsiteRedirect: (id, data) => api.patch(`/website/redirects/${id}`, data),
  deleteWebsiteRedirect: (id) => api.delete(`/website/redirects/${id}`),

  listWebsiteActivity: (params) => api.get('/website/activity', { params }),
};
